lara_django_projects/urls.py
"""_____________________________________________________________________

:PROJECT: LARAsuite

*lara_django_projects urls *

:details: lara_django_projects urls module.
         - add app specific urls here
         - 
:authors: mark doerr <mark.doerr@uni-greifswald.de>

.. note:: -
.. todo:: -
________________________________________________________________________
"""

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView
from django_socio_grpc.settings import grpc_settings
#import lara_django.urls as base_urls

from . import views

# Add your {cookiecutter.project_slug}} urls here.


# !! this sets the apps namespace to be used in the template
app_name = "lara_django_projects"

# companies and institutions should also be added
# the 'name' attribute is used in templates to address the url independent of the view


urlpatterns = [
    # the 'name' value as called by the {% url %} template tag
    path('project/overview', views.RootIndexView.as_view(), name='project-overview'),
    path('project/tree/<uuid:pk>/', views.ProjectTree.as_view(), name='project-tree'),
    path('project/list/', views.ProjectSingleTableView.as_view(), name='project-list'),
    path('project/create/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/update/<uuid:pk>', views.ProjectUpdateView.as_view(), name='project-update'),
    path('project/delete/<uuid:pk>', views.ProjectDeleteView.as_view(), name='project-delete'),
    path('project/<uuid:pk>/', views.ProjectDetailView.as_view(), name='project-detail'),

    path('experiment/list/', views.ExperimentSingleTableView.as_view(), name='experiment-list'),
    path('experiment/create/', views.ExperimentCreateView.as_view(), name='experiment-create'),
    path('experiment/update/<uuid:pk>', views.ExperimentUpdateView.as_view(), name='experiment-update'),
    path('experiment/delete/<uuid:pk>', views.ExperimentDeleteView.as_view(), name='experiment-delete'),
    path('experiment/<uuid:pk>/', views.ExperimentDetailView.as_view(), name='experiment-detail'),

   
    path('details/<uuid:pk>/', views.ProjectDetails.as_view(), name='project-details'),
    #path('<uuid:pk>/', views.ProjectTree.as_view(), name='project-tree'),
    #path('experiments/<uuid:pk>/', views.ExperimentDetails.as_view(),
    #     name='experiment-details'),

    
    path('', views.ProjectSingleTableView.as_view(), name='project-root'),

    # ~ path('^projectslist$', views.projectsList, name='projects-list'), # projects as a long list/table
    #~ path('search/', views.searchForm, name='searchForm'),
    #~ path('search-results/', views.search, name='search'),
    #~ path('results/', views.results, name='results'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns = [
#     path('', views.EntitySingleTableView.as_view(), name='entity-list-root'),
#     path('entities/list/', views.EntitySingleTableView.as_view(), name='entity-list'),
#     path('addresses/list/', views.AddressesListView.as_view(), name='address-list'),
#     path('addresses/create/', views.AddressCreateView.as_view(),
#          name='address-create'),
#     path('addresses/update/<uuid:pk>', views.AddressUpdateView.as_view(),
#          name='address-update'),
#     path('addresses/delete/<uuid:pk>', views.AddressDeleteView.as_view(),
#          name='address-delete'),
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# register handlers in settings
grpc_settings.user_settings["GRPC_HANDLERS"] = [
    "lara_django_projects.grpc_if.handlers.grpc_handlers"]

lara_django_projects/templates/lara_django_projects/create_form.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
</div>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% crispy form %}

{% endblock %}

lara_django_projects/templates/lara_django_projects/delete_form.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2"> {{ section_title }} </h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <a href="{% url delete_link  object.pk %}" class="btn btn-danger" role="button">Edit Item</a>

    </div>
  </div>
</div>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<form method="post">
  <div>
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
  </div>
</form>

{% endblock %}

lara_django_projects/templates/lara_django_projects/experiment_detail.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url update_link  object.pk %}" class="btn btn-warning" role="button">Edit Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<h1>{{ object.name_full }} ({{ object.category }})</h1>

<ul>
    <li>
        {{ object.name_full }}
    </li>
    <li>
        {{ object.name }}
    </li>
</ul>

{% if object.experiments %}
    
<h1>Experiments</h1>

<ul>
 {% for experiment in  object.experiments.all %}
   <li> {{experiment.name}} </li> 
 {% endfor %}
 </ul>       
 
{% else %}
<p>No experiments are available.</p>
{% endif %}
{% endblock %}

lara_django_projects/templates/lara_django_projects/extradata_detail.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url update_link  object.pk %}" class="btn btn-warning" role="button">Edit Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<h1>{{ object.name }} ({{ object.description }})</h1>

<ul>
    <li>

    </li>
    <li>

    </li>
</ul>
{% endblock %}

lara_django_projects/templates/lara_django_projects/list.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url create_link %}" class="btn btn-warning btn-sm btn-outline-secondary" role="button">Add</a>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="sync"></span>
            Sync
        </button>
    </div>
</div>
{% endblock %}

{% load render_table from django_tables2 %}

{% block content%}
{% render_table table %}
{% endblock %}

lara_django_projects/templates/lara_django_projects/project_detail.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url update_link  object.pk %}" class="btn btn-warning" role="button">Edit Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% block content %}

<h1>{{ object.name_full }} ({{ object.category }})</h1>

<p> {{object.description}} </p>
<p> <b>Users</b>: {% for user in object.users.all  %} {{user.acronym}}, {% endfor %} 
</p>
<p> Start date: {{object.datetime_start}} </p>

<ul>
    <li>
        {{ object.name_full }}
    </li>
    <li>
        {{ object.name }}
    </li>
</ul>

{% if object.experiments %}
    
<h1>Experiments</h1>

<ul>
 {% for experiment in  object.experiments.all %}
   <li> 
      <a class="la_tree_item"  href="{% url 'lara_django_projects:experiment-detail' experiment.experiment_id %}" title={{ experiment.description }}>{{experiment.name}} </a> 
   </li> 
 {% endfor %}
 </ul>       
 
{% else %}
<p>No experiments are available.</p>
{% endif %}
{% endblock %}

lara_django_projects/templates/lara_django_projects/project_list.html
{% extends 'lara_django_base/lara_base_menu.html' %}
{% load mptt_tags %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ subtree_root.title }} - Projects </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url create_link %}" class="btn btn-warning btn-sm btn-outline-secondary" role="button">Add</a>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="sync"></span>
            Sync
        </button>
    </div>
</div>
{% endblock %}

{% block content %}
{% if project_list %}
<ul>
  {% recursetree project_list %}
  <li>
    {% if node.is_leaf_node %}
    <a class="la_tree_item" href="{% url 'lara_django_projects:project-detail' node.project_id %}" title={{ node.description }}> {{ node.title }} </a>
    <p>{{ node.description }} </p>
    {% else %}
    <a class="la_subtree" href="{% url 'lara_django_projects:project-tree' node.project_id %}" title={{ node.description }}> {{ node.title }} </a>
    <p>{{ node.description }} </p>
    {% endif %}

    {% if not node.is_leaf_node %}
    <ul class="children">
      {{ children }}
    </ul>
    {% endif %}
  </li>
  {% endrecursetree %}
</ul>
{% else %}
<p>No sub-projects are available.</p>
{% endif %}

{% endblock %}

lara_django_projects/templates/lara_django_projects/root_index.html
{% extends 'lara_django_base/lara_base_menu.html' %}


{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url create_link %}" class="btn btn-warning btn-sm btn-outline-secondary" role="button">Add</a>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
        </div>
        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="sync"></span>
            Sync
        </button>
    </div>
</div>
{% endblock %}

{% block content %}
{% if root_projects %}
<ul>
    {% for mproj in root_projects %}
    <li>
        <a href="{% url 'lara_django_projects:project-tree' mproj.project_id %}" title={{ mproj.description }}>
            {{ mproj.title }} </a>
        <p>{{ mproj.description }} </p>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No main projects are available.</p>
{% endif %}

{% endblock %}

lara_django_projects/templates/lara_django_projects/update_form.html
{% extends 'lara_django_base/lara_base_menu.html' %}

{% block toolbar %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"> {{ section_title }} </h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            <a href="{% url delete_link  object.pk %}" class="btn btn-danger" role="button">Delete Item</a>

        </div>
    </div>
</div>
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% crispy form %}

{% endblock %}